---
- name: Add user with a specific ssh key
  hosts: all
  become: true
  vars_files:
    - users.json

  tasks:
    - name: Create a new user
      ansible.builtin.user:
        name: "{{ item.username }}"
        password: "{{ lookup('file', item.pswd_hash_path) }}"
      with_items: "{{ users }}"

    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: "{{ item.username }}"
        key: "{{ lookup('file', item.pubkey_path) }}"
      with_items: "{{ users }}"

    - name: Enable Pubkey Authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
        state: present
      notify:
        - Restart sshd

    - name: Disable Root Login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
      notify:
        - Restart sshd

  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
