apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - name: http-app-port
      # port could be set smth other, but not the targetPort
      port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.port }}