apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-app
  namespace: http-app-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-app
  template:
    metadata:
      labels:
        app: http-app
    spec:
      containers:
        - name: app-container
          # image: nyuuuukie/test-task-app:linux-arm64-v1.0
          image: nyuuuukie/test-task-app:linux-amd64-v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
          - name: UUID
            valueFrom:
            fieldRef:
              fieldPath: metadata.uid
          - name: AUTHOR
            value: nyuuuukie
          - name: PORT
            value: 8000
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 20
