apiVersion: v1
kind: Service
metadata:
  name: http-app-service
  namespace: http-app-namespace
spec:
  selector:
    app: http-app
  ports:
    - name: http-app-port
      port: 8000
      targetPort: 8000